---
- include_tasks: install.yml
  tags: ["install", "initial-setup"]


- include_tasks: config.yml
  when: not pg_client_only

- name: ensure postgresql is started
  service: name=postgresql state=started
  when: not pg_client_only
